### PR TITLE
added student's t-test to debug menu

### PR DESCRIPTION
**Pull request by joendter**
displays estimate of probability that both AIs are equally good

### CODE REVIEW

**Comment by BelTol3011** [comment]
It would be nice to have a way to turn this off.

**Comment by joendter** [comment]
write one...
add more settings to the config thingy and let *it* toggle all kinds of debug info

**Comment by BelTol3011** [comment]
@joendter 
Okay, I'm going to do that.

**Comment by BelTol3011** [comment]
We need to update the wiki accordingly when we merge.

**Comment by BelTol3011** [comment]
I updated the wiki now.

**Pull request merged**
